"""Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
斐波纳契
By considering the terms in the Fibonacci sequence whose values do not exceed four million,
find the sum of the even-valued terms.
"""


def Fibonacci(number):
    '''斐波纳契示例算法'''
    a = 1
    b=2
    print("%s\n%s"%(a,b))
    for time in range(2, number):
        finalResult=a+b
        a=b
        b=finalResult
        print(finalResult)
def notExceedNumber(maxnumber):
    '''值不能超过某个数值'''
    if(maxnumber<=2):return
    a = 1
    b = 2
    finalResult=0
    evenSet=set()
    evenSet.add(b)
    while(finalResult<maxnumber):
        finalResult = a + b
        a = b
        b = finalResult
        if finalResult%2==0:
            evenSet.add(finalResult)

    print("max:%s ,finalResult:%s,没超过"%(maxnumber,finalResult))
    sumEven=sum(evenSet)
    print("The question2 of result is: %s"%sumEven)

Fibonacci(10)
notExceedNumber(4000000)
